coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5
    patch:
      default:
        target: 75
ignore:
  - "test/"
  - "object_storage_api/v1/*" # ignore routers as they are tested in the e2e tests
