services:
  object-storage-api:
    container_name: object_storage_api_container
    build: .
    volumes:
      - ./object_storage_api:/object-storage-api-run/object_storage_api
    ports:
      - 8000:8000
    restart: on-failure

  mongo-db:
    image: mongo:7.0-jammy
    container_name: mongodb_container
    volumes:
      - ./mongodb/data:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
