version: "3.9"

services:
  object-storage-api:
    container_name: object_storage_api_container
    build: .
    volumes:
      - ./object_storage_api:/object-storage-api-run/object_storage_api
    ports:
      - 8000:8000
    restart: on-failure
