[project]
name = "object-storage_api"
description = "Python microservice providing an API for handling attachments and images in an S3 object store."
readme = "README.md"
requires-python = ">=3.12"
version = "0.0.1"

dependencies = [
    "cryptography",
    "fastapi[all]",
    "PyJWT",
    "pymongo",
    "boto3"
]

[project.urls]
"Repository" = "https://github.com/ral-facilities/object-storage-api"

[project.optional-dependencies]
code-analysis = [
    "pylint==3.3.0",
    "object-storage-api[test]"
]

formatting = [
    "black==24.8.0"
]

test = [
    "pytest==8.3.3",
    "pytest-asyncio==0.24.0",
    "pytest-cov==5.0.0",
    "pytest-env==1.1.5"
]

dev = [
    "object-storage-api[code-analysis]",
    "object-storage-api[formatting]",
    "object-storage-api[test]",
]

[tool.setuptools]
packages = ["object_storage_api"]
