[project]
name = "object-storage_api"
description = "Python microservice providing an API for handling attachments and images in an S3 object store."
readme = "README.md"
requires-python = ">=3.12"
version = "0.0.1"

dependencies = [
    "cryptography==42.0.8",
    "fastapi[all]==0.111.0",
    "PyJWT==2.8.0",
    "pymongo==4.8.0",
    "uvicorn==0.30.1"
]

[project.urls]
"Repository" = "https://github.com/ral-facilities/object-storage-api"

[project.optional-dependencies]
code-analysis = [
    "pylint==3.2.5",
    "object-storage-api[test]"
]

formatting = [
    "black==24.4.2"
]

test = [
    "pytest==8.2.2",
    "pytest-asyncio==0.23.7",
    "pytest-cov==5.0.0",
    "pytest-env==1.1.3"
]

scripts = [
    "faker==26.0.0",
    "requests==2.32.3"
]

dev = [
    "object-storage-api[code-analysis]",
    "object-storage-api[formatting]",
    "object-storage-api[test]",
    "object-storage-api[scripts]"
]

[tool.setuptools]
packages = ["object_storage_api"]
