[project]
name = "object-storage-api"
description = "Python microservice providing an API for handling attachments and images in an S3 object store."
readme = "README.md"
requires-python = ">=3.13"
version = "1.0.0"

dependencies = [
    "cryptography",
    "fastapi[all]",
    "PyJWT",
    "pymongo",
    "boto3",
    "Pillow"
]

[project.urls]
"Repository" = "https://github.com/ral-facilities/object-storage-api"

[project.optional-dependencies]
code-analysis = [
    "black==25.11.0",
    "pylint==4.0.4",
    "object-storage-api[test]"
]

test = [
    "pytest==9.0.1",
    "pytest-asyncio==1.3.0",
    "pytest-cov==7.0.0",
    "pytest-env==1.2.0",
    "requests==2.32.5"
]

scripts = [
    "faker==38.2.0",
    "faker-file[pdf,docx,images]==0.18.4",
]

dev = [
    "object-storage-api[code-analysis]",
    "object-storage-api[test]",
    "object-storage-api[scripts]",
]

[tool.coverage.run]
omit = [
    # Exclude test code from coverage measurement
    "test/*",
    # Exclude routers from coverage measurement as they are tested in the e2e tests
    "object_storage_api/v1/*"
]

[tool.setuptools.packages.find]
include  = ["object_storage_api", "object_storage_api*"]
