"""
Collection of some utility functions used by services
"""

# pylint:disable=fixme
# TODO: Some of this file is identical to the one in inventory-management-system-api - Use common repo?

import logging
import re

logger = logging.getLogger()


def generate_code(name: str, entity_type: str) -> str:
    """
    Generate a code for an entity based on its name. This is used to maintain uniqueness and prevent
    duplicates. (E.g. a duplicate subcategories within a category)

    The code is generated by converting the name to lowercase and replacing spaces with hyphens. Leading and
    trailing spaces are removed, and consecutive spaces are replaced with a single hyphen

    :param name: The name of the entity
    :param entity_type: Name of the entity type e.g. catalogue category/system (Used for logging)
    :return: The generated code for the entity
    """
    logger.info("Generating code for the %s based on its name", entity_type)
    name = name.lower().strip()
    return re.sub(r"\s+", "-", name)
