name: CI
on:
  workflow_dispatch:
    inputs:
      push-docker-image-to-harbor:
        description: 'Push Docker Image to Harbor'
        type: boolean
        default: false
  pull_request:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[code-analysis]

      - name: Run black
        run: black --check --line-length 120 object_storage_api test

      - name: Run pylint
        run: pylint object_storage_api test

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Create logging configuration file
        run: cp object_storage_api/logging.example.ini object_storage_api/logging.ini

      - name: Run unit tests
        run: |
          docker build --file Dockerfile --target test --tag object-storage-api:test .
          docker run \
           --name object-storage-api \
           object-storage-api:test \
           pytest --config-file test/pytest.ini --cov object_storage_api --cov-report xml test/unit -v
          docker cp object-storage-api:/app/coverage.xml coverage.xml

      - name: Upload coverage reports to Codecov
        if: success()
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  e2e-tests:
    needs: [unit-tests]
    name: End-to-End Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Create logging configuration file
        run: cp object_storage_api/logging.example.ini object_storage_api/logging.ini

      # Sleep 10 seconds to give time for containers to start
      - name: Start MongoDB and MinIO
        run: |
          docker compose up --detach mongo-db minio
          sleep 10
      - name: Create MinIO buckets
        run: |
          docker compose up minio-create-buckets

      - name: Run e2e tests
        run: |
          docker build --file Dockerfile --target test --tag object-storage-api:test .
          docker run \
           --name object-storage-api \
           --add-host localhost:host-gateway \
           object-storage-api:test \
           pytest --config-file test/pytest.ini test/e2e -v

      - name: Output docker logs (mongodb)
        if: failure()
        run: docker logs object-storage-api-mongodb

      - name: Output docker logs (minio)
        if: failure()
        run: docker logs object-storage-minio

  docker:
    # This job triggers only if all the other jobs succeed. It builds the Docker image 
    # and if run manually from Github Actions, it pushes to Harbor.
    needs: [linting, unit-tests, e2e-tests]
    name: Docker
    runs-on: ubuntu-latest
    env:
      PUSH_DOCKER_IMAGE_TO_HARBOR: ${{ inputs.push-docker-image-to-harbor != null && inputs.push-docker-image-to-harbor || 'false' }}
    steps:
      - name: Check out repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: ${{ vars.HARBOR_URL }}/object-storage-api

      - name: Login to Harbor
        if: ${{ fromJSON(env.PUSH_DOCKER_IMAGE_TO_HARBOR) }}
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ vars.HARBOR_URL }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: ${{ fromJSON(env.PUSH_DOCKER_IMAGE_TO_HARBOR) && 'Build and push Docker image to Harbor' || 'Build Docker image' }}
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: .
          push: ${{ fromJSON(env.PUSH_DOCKER_IMAGE_TO_HARBOR) }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: prod
